server:
    port: 9999
    servlet:
      context-path: /
      encoding:
        charset: UTF-8
        force: true
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/study
    username: root
    password: 1
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
        hibernate:
          show_sql: false
          format_sql: true
          highlight_sql: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace

REST_API_KEY: "your key"
